/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedCheckerRouteImport } from './routes/_authenticated/checker'
import { Route as AuthenticatedBillingTestRouteImport } from './routes/_authenticated/billing-test'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedBuilderJobIdRouteImport } from './routes/_authenticated/builder.$jobId'
import { Route as ApiPublicExtensionJobsRouteImport } from './routes/api/public/extension/jobs'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckerRoute = AuthenticatedCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingTestRoute =
  AuthenticatedBillingTestRouteImport.update({
    id: '/billing-test',
    path: '/billing-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBuilderJobIdRoute =
  AuthenticatedBuilderJobIdRouteImport.update({
    id: '/builder/$jobId',
    path: '/builder/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicExtensionJobsRoute = ApiPublicExtensionJobsRouteImport.update({
  id: '/api/public/extension/jobs',
  path: '/api/public/extension/jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/billing-test': typeof AuthenticatedBillingTestRoute
  '/checker': typeof AuthenticatedCheckerRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/builder/$jobId': typeof AuthenticatedBuilderJobIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/extension/jobs': typeof ApiPublicExtensionJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/billing-test': typeof AuthenticatedBillingTestRoute
  '/checker': typeof AuthenticatedCheckerRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/builder/$jobId': typeof AuthenticatedBuilderJobIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/extension/jobs': typeof ApiPublicExtensionJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/billing-test': typeof AuthenticatedBillingTestRoute
  '/_authenticated/checker': typeof AuthenticatedCheckerRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/builder/$jobId': typeof AuthenticatedBuilderJobIdRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/extension/jobs': typeof ApiPublicExtensionJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/billing'
    | '/billing-test'
    | '/checker'
    | '/generate'
    | '/jobs'
    | '/resumes'
    | '/settings'
    | '/builder/$jobId'
    | '/api/public/razorpay-webhook'
    | '/api/public/extension/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/billing'
    | '/billing-test'
    | '/checker'
    | '/generate'
    | '/jobs'
    | '/resumes'
    | '/settings'
    | '/builder/$jobId'
    | '/api/public/razorpay-webhook'
    | '/api/public/extension/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/billing'
    | '/_authenticated/billing-test'
    | '/_authenticated/checker'
    | '/_authenticated/generate'
    | '/_authenticated/jobs'
    | '/_authenticated/resumes'
    | '/_authenticated/settings'
    | '/_authenticated/builder/$jobId'
    | '/api/public/razorpay-webhook'
    | '/api/public/extension/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicExtensionJobsRoute: typeof ApiPublicExtensionJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checker': {
      id: '/_authenticated/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof AuthenticatedCheckerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing-test': {
      id: '/_authenticated/billing-test'
      path: '/billing-test'
      fullPath: '/billing-test'
      preLoaderRoute: typeof AuthenticatedBillingTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/builder/$jobId': {
      id: '/_authenticated/builder/$jobId'
      path: '/builder/$jobId'
      fullPath: '/builder/$jobId'
      preLoaderRoute: typeof AuthenticatedBuilderJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/extension/jobs': {
      id: '/api/public/extension/jobs'
      path: '/api/public/extension/jobs'
      fullPath: '/api/public/extension/jobs'
      preLoaderRoute: typeof ApiPublicExtensionJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBillingTestRoute: typeof AuthenticatedBillingTestRoute
  AuthenticatedCheckerRoute: typeof AuthenticatedCheckerRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBuilderJobIdRoute: typeof AuthenticatedBuilderJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBillingTestRoute: AuthenticatedBillingTestRoute,
  AuthenticatedCheckerRoute: AuthenticatedCheckerRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBuilderJobIdRoute: AuthenticatedBuilderJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicExtensionJobsRoute: ApiPublicExtensionJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
