REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.owns_workspace(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_active_pro(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.try_consume_prompt(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.owns_workspace(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_active_pro(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.try_consume_prompt(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;